spring.application.name=api-gateway

jwt.secret=${SPRING_JWT_SECRET}
jwt.expiration=3600000

spring.r2dbc.url=r2dbc:postgresql://${PGHOST}/${PGDATABASE}?sslmode=require
spring.r2dbc.username=${PGUSER}
spring.r2dbc.password=${PGPASSWORD}

routes.query-service-uri=http://localhost:8081
routes.command-service-uri=http://localhost:8082